{"identifier":{"url":"doc:\/\/com.napcosecurity.NapcoILockSDK\/documentation\/NapcoILockSDK","interfaceLanguage":"swift"},"primaryContentSections":[{"content":[{"type":"heading","text":"Overview","anchor":"Overview","level":2},{"inlineContent":[{"text":"The NapcoILockSDK simplifies the integration of smart locks into your applications by providing a set of tools and APIs for connection, control, and interaction with locks. The SDK includes key components such as the ","type":"text"},{"identifier":"doc:\/\/com.napcosecurity.NapcoILockSDK\/documentation\/NapcoILockSDK\/Credential","type":"reference","isActive":true},{"type":"text","text":" struct for handling authentication data, "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.napcosecurity.NapcoILockSDK\/documentation\/NapcoILockSDK\/ImportUtility"},{"text":" class for importing and decoding lock credentials, and the ","type":"text"},{"identifier":"doc:\/\/com.napcosecurity.NapcoILockSDK\/documentation\/NapcoILockSDK\/iLock","type":"reference","isActive":true},{"text":" class for managing lock operations, and enums for lock states and keypad inputs. With built-in support for delegate-driven communication, the SDK allows you to monitor lock status, RSSI levels, and handle operational mismatches effectively. Designed for flexibility and ease of use, the SDK can be integrated into a variety of smart home or access control systems.","type":"text"}],"type":"paragraph"},{"anchor":"Installation","text":"Installation","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Follow these steps to integrate the ","type":"text"},{"type":"emphasis","inlineContent":[{"type":"text","text":"NapcoILockSDK"}]},{"type":"text","text":" into your project:"}]},{"type":"heading","anchor":"Step-1-Add-the-Framework","level":4,"text":"Step 1: Add the Framework"},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Get the ","type":"text"},{"type":"codeVoice","code":"NapcoILockSDK.xcframework"},{"text":".","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"In your Xcode project:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Go to ","type":"text"},{"inlineContent":[{"text":"Project Navigator","type":"text"}],"type":"emphasis"},{"type":"text","text":" → Select your project."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Under "},{"type":"emphasis","inlineContent":[{"text":"General","type":"text"}]},{"type":"text","text":" → "},{"inlineContent":[{"text":"Frameworks, Libraries, and Embedded Content","type":"text"}],"type":"emphasis"},{"type":"text","text":", click the "},{"type":"emphasis","inlineContent":[{"type":"text","text":"+"}]},{"type":"text","text":" button."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Select ","type":"text"},{"inlineContent":[{"type":"text","text":"Add Other…"}],"type":"emphasis"},{"type":"text","text":" → "},{"inlineContent":[{"text":"Add Files…","type":"text"}],"type":"emphasis"},{"text":" and choose the ","type":"text"},{"code":"NapcoILockSDK.xcframework","type":"codeVoice"},{"text":".","type":"text"}]}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Ensure that the framework is set to "},{"type":"emphasis","inlineContent":[{"type":"text","text":"Embed & Sign"}]},{"text":".","type":"text"}]}]}]},{"inlineContent":[{"identifier":"add_framework_screenshot.png","type":"image"}],"type":"paragraph"},{"type":"heading","text":"Step 2: Add a Bluetooth Usage Description","level":4,"anchor":"Step-2-Add-a-Bluetooth-Usage-Description"},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Open your project’s "},{"inlineContent":[{"text":"Info.plist","type":"text"}],"type":"emphasis"},{"type":"text","text":" file."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Add a new entry with the key:","type":"text"},{"type":"text","text":"\n"},{"inlineContent":[{"code":"Privacy - Bluetooth Always Usage Description","type":"codeVoice"}],"type":"emphasis"},{"type":"text","text":""},{"type":"text","text":"\n"},{"type":"text","text":"and set its value to a description string explaining why your app needs Bluetooth access (e.g., "},{"code":"\"This app uses Bluetooth to connect to smart locks.\"","type":"codeVoice"},{"type":"text","text":")."}]}]}]},{"type":"paragraph","inlineContent":[{"identifier":"add_purose_string_screenshot.png","type":"image"}]},{"level":2,"anchor":"Usage-Overview","type":"heading","text":"Usage Overview"},{"anchor":"To-use-the-iLock-SDK-you-need-to-initialize-it-first-After-initialization-is-complete-you-can-use-other-functionalities","level":6,"type":"heading","text":"To use the iLock SDK, you need to initialize it first. After initialization is complete, you can use other functionalities."},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Create a property for the iLockSDKInitializer in your ViewController or AppDelegate:","type":"text"}]}]}]},{"code":["let sdkInitializer: iLockSDKInitializer = iLockSDKInitializer()"],"type":"codeListing","syntax":"swift"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Initialize the SDK with your application ID:"}]}]}],"start":2,"type":"orderedList"},{"syntax":"swift","code":["   sdkInitializer.initialize(appId: \"yourAppId\") { result in","       switch result {","       case .success():","           print(\"SDK initialized successfully\")","       case .failure(let error):","           print(\"Failed to initialize SDK: \\(error)\")","       }","   }"],"type":"codeListing"},{"anchor":"To-unlock-or-toggle-a-lock-follow-these-steps","type":"heading","text":"To unlock or toggle a lock, follow these steps:","level":6},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Initialize an ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.napcosecurity.NapcoILockSDK\/documentation\/NapcoILockSDK\/iLock","type":"reference"},{"type":"text","text":" instance with the broadcast ID and optionally set the RSSI threshold:"}]},{"code":["let lock = iLock(broadcastId: \"ABC123\", rssiThreshold: -50)"],"syntax":"swift","type":"codeListing"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Call the connect method to connect to the lock:","type":"text"}]},{"syntax":"swift","code":["lock.connect()"],"type":"codeListing"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Wait for the ","type":"text"},{"type":"codeVoice","code":"onLockConnected"},{"text":" callback from the delegate to confirm the connection.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Immediately call the unlock or toggle method with a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.napcosecurity.NapcoILockSDK\/documentation\/NapcoILockSDK\/Credential","type":"reference"},{"type":"text","text":":"}]},{"syntax":"swift","code":["lock.unlock(cred: credential)"],"type":"codeListing"},{"inlineContent":[{"text":"OR","type":"text"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["lock.toggle(cred: credential, type: .unlock)"]}]}]},{"anchor":"To-send-keypad-key-commands-follow-these-steps","level":6,"type":"heading","text":"To send keypad key commands, follow these steps:"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Initialize an "},{"type":"reference","identifier":"doc:\/\/com.napcosecurity.NapcoILockSDK\/documentation\/NapcoILockSDK\/iLock","isActive":true},{"type":"text","text":" instance with the broadcast ID and optionally set the RSSI threshold."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Call the connect method to connect to the lock.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Wait for the "},{"type":"codeVoice","code":"onLockConnected"},{"text":" callback from the delegate to confirm the connection.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Immediately call the unlock method with a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.napcosecurity.NapcoILockSDK\/documentation\/NapcoILockSDK\/Credential"},{"text":".","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Once the lock status is reported as Unlocked, you can display the keypad interface and send keypad commands:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["lock.keyPress(key: .five)"]}]}],"type":"orderedList"}],"kind":"content"}],"topicSections":[{"identifiers":["doc:\/\/com.napcosecurity.NapcoILockSDK\/documentation\/NapcoILockSDK\/ImportUtility","doc:\/\/com.napcosecurity.NapcoILockSDK\/documentation\/NapcoILockSDK\/iLock","doc:\/\/com.napcosecurity.NapcoILockSDK\/documentation\/NapcoILockSDK\/iLockSDKInitializer"],"anchor":"Classes","generated":true,"title":"Classes"},{"identifiers":["doc:\/\/com.napcosecurity.NapcoILockSDK\/documentation\/NapcoILockSDK\/iLockDelegate"],"generated":true,"title":"Protocols","anchor":"Protocols"},{"title":"Structures","identifiers":["doc:\/\/com.napcosecurity.NapcoILockSDK\/documentation\/NapcoILockSDK\/Credential","doc:\/\/com.napcosecurity.NapcoILockSDK\/documentation\/NapcoILockSDK\/LockData"],"anchor":"Structures","generated":true},{"generated":true,"title":"Enumerations","identifiers":["doc:\/\/com.napcosecurity.NapcoILockSDK\/documentation\/NapcoILockSDK\/KeypadKey","doc:\/\/com.napcosecurity.NapcoILockSDK\/documentation\/NapcoILockSDK\/LockStatus","doc:\/\/com.napcosecurity.NapcoILockSDK\/documentation\/NapcoILockSDK\/ToggleType","doc:\/\/com.napcosecurity.NapcoILockSDK\/documentation\/NapcoILockSDK\/iLockSDKInitializerError"],"anchor":"Enumerations"}],"metadata":{"roleHeading":"Framework","role":"collection","title":"NapcoILockSDK","externalID":"NapcoILockSDK","symbolKind":"module","modules":[{"name":"NapcoILockSDK"}]},"abstract":[{"type":"text","text":"The NapcoILockSDK provides a comprehensive framework for connecting, controlling, and managing smart Napco locks using Bluetooth, with support for credential-based unlocking, toggling and lock status monitoring."}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/napcoilocksdk"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/napcoilocksdk"]}],"sections":[],"hierarchy":{"paths":[[]]},"references":{"doc://com.napcosecurity.NapcoILockSDK/documentation/NapcoILockSDK/iLockSDKInitializer":{"identifier":"doc:\/\/com.napcosecurity.NapcoILockSDK\/documentation\/NapcoILockSDK\/iLockSDKInitializer","kind":"symbol","role":"symbol","title":"iLockSDKInitializer","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iLockSDKInitializer","kind":"identifier"}],"type":"topic","url":"\/documentation\/napcoilocksdk\/ilocksdkinitializer","abstract":[{"type":"text","text":"Provides  functionality to initialize the SDK with an application ID."}],"navigatorTitle":[{"text":"iLockSDKInitializer","kind":"identifier"}]},"doc://com.napcosecurity.NapcoILockSDK/documentation/NapcoILockSDK/Credential":{"abstract":[{"type":"text","text":"Represents a credential."}],"kind":"symbol","role":"symbol","url":"\/documentation\/napcoilocksdk\/credential","type":"topic","identifier":"doc:\/\/com.napcosecurity.NapcoILockSDK\/documentation\/NapcoILockSDK\/Credential","navigatorTitle":[{"text":"Credential","kind":"identifier"}],"title":"Credential","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Credential"}]},"add_framework_screenshot.png":{"identifier":"add_framework_screenshot.png","alt":"Adding the Framework","type":"image","variants":[{"url":"\/images\/com.napcosecurity.NapcoILockSDK\/add_framework_screenshot.png","traits":["1x","light"]}]},"doc://com.napcosecurity.NapcoILockSDK/documentation/NapcoILockSDK/KeypadKey":{"navigatorTitle":[{"kind":"identifier","text":"KeypadKey"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeypadKey"}],"kind":"symbol","title":"KeypadKey","url":"\/documentation\/napcoilocksdk\/keypadkey","abstract":[{"type":"text","text":"Represents the keys on a keypad."}],"role":"symbol","identifier":"doc:\/\/com.napcosecurity.NapcoILockSDK\/documentation\/NapcoILockSDK\/KeypadKey"},"doc://com.napcosecurity.NapcoILockSDK/documentation/NapcoILockSDK/ImportUtility":{"identifier":"doc:\/\/com.napcosecurity.NapcoILockSDK\/documentation\/NapcoILockSDK\/ImportUtility","kind":"symbol","role":"symbol","title":"ImportUtility","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ImportUtility","kind":"identifier"}],"type":"topic","url":"\/documentation\/napcoilocksdk\/importutility","abstract":[{"text":"A utility class for importing and decoding lock credentials.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ImportUtility"}]},"doc://com.napcosecurity.NapcoILockSDK/documentation/NapcoILockSDK/LockStatus":{"kind":"symbol","identifier":"doc:\/\/com.napcosecurity.NapcoILockSDK\/documentation\/NapcoILockSDK\/LockStatus","url":"\/documentation\/napcoilocksdk\/lockstatus","role":"symbol","abstract":[{"type":"text","text":"Represents the lock’s current status."}],"type":"topic","title":"LockStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LockStatus","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"LockStatus"}]},"add_purose_string_screenshot.png":{"identifier":"add_purose_string_screenshot.png","alt":"Adding the Framework","type":"image","variants":[{"url":"\/images\/com.napcosecurity.NapcoILockSDK\/add_purose_string_screenshot.png","traits":["1x","light"]}]},"doc://com.napcosecurity.NapcoILockSDK/documentation/NapcoILockSDK/NapcoILockSDKVersionNumber":{"kind":"symbol","identifier":"doc:\/\/com.napcosecurity.NapcoILockSDK\/documentation\/NapcoILockSDK\/NapcoILockSDKVersionNumber","url":"\/documentation\/napcoilocksdk\/napcoilocksdkversionnumber","role":"symbol","abstract":[{"text":"Project version number for NapcoILockSDK.","type":"text"}],"type":"topic","title":"NapcoILockSDKVersionNumber","fragments":[{"kind":"identifier","text":"NapcoILockSDKVersionNumber"}]},"doc://com.napcosecurity.NapcoILockSDK/documentation/NapcoILockSDK/iLockSDKInitializerError":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"iLockSDKInitializerError","kind":"identifier"}],"url":"\/documentation\/napcoilocksdk\/ilocksdkinitializererror","abstract":[],"type":"topic","identifier":"doc:\/\/com.napcosecurity.NapcoILockSDK\/documentation\/NapcoILockSDK\/iLockSDKInitializerError","title":"iLockSDKInitializerError","role":"symbol","navigatorTitle":[{"text":"iLockSDKInitializerError","kind":"identifier"}]},"doc://com.napcosecurity.NapcoILockSDK/documentation/NapcoILockSDK":{"abstract":[{"text":"The NapcoILockSDK provides a comprehensive framework for connecting, controlling, and managing smart Napco locks using Bluetooth, with support for credential-based unlocking, toggling and lock status monitoring.","type":"text"}],"url":"\/documentation\/napcoilocksdk","kind":"symbol","type":"topic","title":"NapcoILockSDK","role":"collection","identifier":"doc:\/\/com.napcosecurity.NapcoILockSDK\/documentation\/NapcoILockSDK"},"doc://com.napcosecurity.NapcoILockSDK/documentation/NapcoILockSDK/NapcoILockSDKVersionString":{"title":"NapcoILockSDKVersionString","url":"\/documentation\/napcoilocksdk\/napcoilocksdkversionstring","identifier":"doc:\/\/com.napcosecurity.NapcoILockSDK\/documentation\/NapcoILockSDK\/NapcoILockSDKVersionString","abstract":[{"text":"Project version string for NapcoILockSDK.","type":"text"}],"kind":"symbol","fragments":[{"text":"NapcoILockSDKVersionString","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.napcosecurity.NapcoILockSDK/documentation/NapcoILockSDK/iLockDelegate":{"title":"iLockDelegate","abstract":[{"text":"A protocol defining delegate methods for receiving events from the lock.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"iLockDelegate"}],"url":"\/documentation\/napcoilocksdk\/ilockdelegate","navigatorTitle":[{"kind":"identifier","text":"iLockDelegate"}],"identifier":"doc:\/\/com.napcosecurity.NapcoILockSDK\/documentation\/NapcoILockSDK\/iLockDelegate","type":"topic"},"doc://com.napcosecurity.NapcoILockSDK/documentation/NapcoILockSDK/iLock":{"url":"\/documentation\/napcoilocksdk\/ilock","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"iLock"}],"identifier":"doc:\/\/com.napcosecurity.NapcoILockSDK\/documentation\/NapcoILockSDK\/iLock","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"iLock","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents a BLE enabled smart lock."}],"title":"iLock","type":"topic","kind":"symbol"},"doc://com.napcosecurity.NapcoILockSDK/documentation/NapcoILockSDK/LockData":{"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"LockData","kind":"identifier"}],"url":"\/documentation\/napcoilocksdk\/lockdata","abstract":[{"type":"text","text":"Represents the data required to interact with a lock."}],"type":"topic","identifier":"doc:\/\/com.napcosecurity.NapcoILockSDK\/documentation\/NapcoILockSDK\/LockData","title":"LockData","role":"symbol","navigatorTitle":[{"text":"LockData","kind":"identifier"}]},"doc://com.napcosecurity.NapcoILockSDK/documentation/NapcoILockSDK/ToggleType":{"kind":"symbol","abstract":[{"text":"Represents the toggle action for a lock.","type":"text"}],"url":"\/documentation\/napcoilocksdk\/toggletype","title":"ToggleType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ToggleType"}],"type":"topic","identifier":"doc:\/\/com.napcosecurity.NapcoILockSDK\/documentation\/NapcoILockSDK\/ToggleType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ToggleType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.napcosecurity.NapcoILockSDK\/documentation\/NapcoILockSDK\/NapcoILockSDKVersionNumber","doc:\/\/com.napcosecurity.NapcoILockSDK\/documentation\/NapcoILockSDK\/NapcoILockSDKVersionString"],"anchor":"Variables","generated":true,"title":"Variables"}],"op":"replace","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null}]}]}